[package]
name = "relog"
version = "0.0.1"
authors = ["Andrew <andrew@subarctic.org>"]
license = "MIT"
description = "Strong String Normalization"
edition = "2018"
readme = "README.md"
repository = "https://github.com/andrew-johnson-4/InPlace"
keywords = ["algorithms"]

[[bin]]
name = "relog"
